Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2022-12, with the labels that each got.

#341 [Feat] 버전 업데이트 알림창
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/Version.swift
  HappyAnding/HappyAnding/ViewModel/CheckUpdateVersion.swift
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
  HappyAnding/HappyAnding/Views/LaunchScreenView.swift
Labels: enhancement, 🐡 엘리

#347 [Feat] design 업데이트
  HappyAnding/HappyAnding/Model/SectionType.swift
  HappyAnding/HappyAnding/Views/Components/CustomTextEditor.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement, 🔥 emergency, 🍔 내일은개발천재

#351 Write Curation View UI 변경사항
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: enhancement, 🐈 로겐시

#346 [feat] Searchable UI 변경
  HappyAnding/HappyAnding/Views/SearchView.swift
Labels: enhancement, 🦔 홍기

#352 Write nick name view/text field
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: enhancement, 🍔 내일은개발천재

#349 [Feat] user 정보가 없을 때, 로그인 화면으로 이동시키는 기능 구현
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
Labels: enhancement, 🍔 내일은개발천재

#354 WriteShortcutsView UI 수정
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: bug

#358 [Feat] 큐레이션의 단축어 정렬 기능 추가
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement

#362 Profile icon 이미지 통일
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
Labels: enhancement, 🐈 로겐시

#364 Create LICENSE
  LICENSE
Labels: documentation

#368 [Feat] Admin curation cell/description UI 오류 수정 및 개행문자 변환
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
Labels: bug, enhancement, 🐈 로겐시
