Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2022-11, with the labels that each got.

#115 [Feat] ShortcutsZipViewModel 관련 Shortcut, Curtion 로직 및 데이터 변경
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
Labels: enhancement

#119 [Fix] #118 Navigation Bar Color 및 Back Button 수정
  HappyAnding/HappyAnding/Extensions/Navigationbar+Extension.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
Labels: enhancement

#116 [Feat] EditShortcutView
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement

#126 [Feat] #125 ReadShortcutView 공유버튼 기능 구현
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement

#130 [Feat] 큐레이션 편집 기능 구현
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement, 🔥 emergency

#123 [Feat] #121 - Splash 화면 수정
  HappyAnding/HappyAnding/Views/Launch Screen.storyboard
Labels: enhancement

#128 [Feat] 애플로 로그인 구현
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Assets.xcassets/logo.imageset/Contents.json
  HappyAnding/HappyAnding/Assets.xcassets/logo.imageset/logo.png
  HappyAnding/HappyAnding/HappyAnding.entitlements
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
  HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement, 🔥 emergency

#136 [Feat] 삭제 Alert 및 색상 변경
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement

#138 [Feat] 단축어 cell 패딩 값 수정
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
Labels: enhancement

#140 [Feat] 단축어 상세 뷰 카테고리 UI 변경
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
Labels: enhancement

#142 [Feat] User 모델 변경 및 함수 추가
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Model/User.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement, 🔥 emergency

#137 Write curation set view/navigation back button
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement

#141 [Feat] 단축어 링크 유효성 검사
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement

#144 [Feat] #143 - Icon Symbol 변경
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
Labels: enhancement, 🔥 emergency

#148 [Feat] Curation 모델 변경 및 함수 생성
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement

#156 [Feat] 연관된 앱 입력 방식 수정
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement

#155 [Fix] 큐레이션 설명 작성 화면에서 키보드 내리기
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
Labels: bug

#150 회원가입 관련 이슈 해결
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
  HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: bug, enhancement

#160 [Feat] Category 관련 뷰 디자인 업데이트
  HappyAnding/HappyAnding/Model/Category.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
Labels: enhancement

#164 Shortcuts zip view model
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
Labels: enhancement, 🔥 emergency

#147 [Fix] 탭바 외 기타 등등 UI 변경 요청 사항 반영
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement

#173 [Feat] Design Minor Changes 2
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: bug, enhancement

#180 [Feat] 수정 / 삭제 함수 기능 구현
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Model/Shortcuts.swift
  HappyAnding/HappyAnding/Model/User.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement

#182 [Feat] 데이터 모델 서버시간 반영
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Date+Extension.swift
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/Shortcuts.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement

#184 [Feat] Hide imcomplete functions (공유 및 신고버튼)
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: bug

#174 [Feat] 삭제함수 연결
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement

#166 [Feat] #165 - update explorecategoryView
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
Labels: enhancement

#175 [Fix] Admin curation view 오류 수정
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
Labels: bug

#177 [Feat] 연관앱 입력 방식 수정
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement

#179 Feat] ReadShortcutView 디자인 수정사항
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
Labels: enhancement

#188 [Feat] Shortcuts zip ViewModel 관련 작업 진행
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement

#190 [Feat] 큐레이션 작성시 선택할 수 있는 단축어 제한
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement

#193 [Feat] Design Minor Changes
  HappyAnding/HappyAnding/Model/SectionType.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
Labels: bug, enhancement

#194 [Fix] 글자수가 초과해도 저장되는 이슈
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
Labels: bug

#197 [Feat] ViewModel 뷰 처리
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
Labels: enhancement

#195 [Feat] 닉네임 글자수 제한
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: bug, enhancement

#202 [Feat] Setting view 기능 연결
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MailView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
Labels: enhancement

#162 [Feat] #161 - DarkMode Disable
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
Labels: enhancement

#207 [Feat] ShortcutsListView/infiniteScroll 기능 추가 중
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/SectionType.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
Labels: enhancement

#212 [Feat] 회원가입 뷰, 개인정보처리방침
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Info.plist
  HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
Labels: enhancement, 🍔 내일은개발천재

#209 [Feat] 데이터 수정 시 UI 반영
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: enhancement, 🐡 엘리

#214 [Fix] 로그아웃 버그 해결
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement

#215 [Feat] 스와이프 제스처
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/UINavigationContoller+Extension.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
Labels: enhancement, 🍔 내일은개발천재

#218 [Feat] Add SettingView cells
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/AboutTeamView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/apache.txt
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: enhancement, 🐈 로겐시

#221 [Feat] #206 - DarkMode Color 대응
  HappyAnding/HappyAnding/Assets.xcassets/Colors/SystemColors/Primary.colorset/Contents.json
  HappyAnding/HappyAnding/Extensions/Color+Extension.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement, 🦄 롬희

#224 [Feat] 단축어 한 줄 설명 제한 글자수 변경
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement, 🫒 그린

#227 [FIX] 유저 정보 초기화 함수 선언
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
Labels: 🔥 emergency

#226 [Feat] #223 - SignInApple & NicknameView Darkmode 컬러 대응
  HappyAnding/HappyAnding/Extensions/Color+Extension.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement, 🦄 롬희

#233 [HotFix] 탈퇴하기 기능 및 뷰 구현
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement, 🔥 emergency, 🍔 내일은개발천재, 🐈 로겐시, 🐡 엘리

#241 [Feat] Search view/UI
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
Labels: enhancement

#243 [Feat] search 함수 구현
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutTestModel.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement, 🐡 엘리

#247 [Feat] 특수문자 입력 제한
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/String+Extension.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: enhancement, 🦔 홍기

#249 [Feat] 추천 검색어 서버에서 관리
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/Keyword.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
Labels: enhancement

#252 [Feat] Navigation Stack!!
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Binding.swift
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/ViewModel/NavigationViewModel.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutTestModel.swift
  HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement, 🔥 emergency, 🍔 내일은개발천재, 🫒 그린

#255 Revert "[Feat] Navigation Stack!!"
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Binding.swift
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/ViewModel/NavigationViewModel.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutTestModel.swift
  HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: 🔥 emergency

#267 NavigationStack 구현
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Binding.swift
  HappyAnding/HappyAnding/Model/Curation.swift
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/ViewModel/NavigationViewModel.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: bug, enhancement, 🔥 emergency, 🍔 내일은개발천재, 🫒 그린

#269 [Feat] 모델 변경
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/Comment.swift
  HappyAnding/HappyAnding/Model/FirebaseService.swift
  HappyAnding/HappyAnding/Model/Shortcuts.swift
  HappyAnding/HappyAnding/Model/User.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ShortcutTestModel.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/TestUserCurationListView.swift
Labels: enhancement

#270 [Feat] #254 - Button Disable Color Change
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Color+Extension.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
Labels: enhancement, 🦄 롬희

#274 [Feat] deprecated Alert 교체
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
Labels: enhancement

#276 [Feat] 단축어 업데이트화면 UI
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: enhancement

#277 [Feat] 탭뷰 누르면 첫번째 페이지로 이동
  HappyAnding/HappyAnding/ViewModel/NavigationViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
Labels: enhancement

#280 [Feat] 앱 설치 유저에게 deep link 공유하기
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/URL+Extension.swift
  HappyAnding/HappyAnding/Info.plist
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
Labels: 🦔 홍기

#286 [Feat] stickyheader, button fnction and design change
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
Labels: enhancement, 🐈 로겐시

#292 [Feat] 출시를 위한 댓글 화면 제거
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement, 🐡 엘리

#293 [Feat] 댓글 추가, 삭제 기능 추가
  HappyAnding/HappyAnding/Extensions/View+Extension.swift
  HappyAnding/HappyAnding/Model/Comment.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement

#290 [Feat] ExploreCurationView 바뀐 UI 적용
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
Labels: 🦔 홍기

#296 [Feat] 검색 기능 업그레이드
  HappyAnding/HappyAnding/Views/SearchView.swift
Labels: enhancement, 🐡 엘리

#305 [Feat] 다운로드 버튼 기능 업데이트
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement, 🐡 엘리

#307 [Feat] 댓글 수정 + 네비게이션바 버튼 통일
  HappyAnding/HappyAnding/Extensions/Navigationbar+Extension.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement, 🐡 엘리

#300 [Feat] curation deeplink 기능 추가
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement, 🦔 홍기

#311 [Fix] 회원탈퇴 에러
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
Labels: enhancement, 🐡 엘리

#309 [Feat] 모달에 핸들 및 닫기 버튼 추가
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
  HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: enhancement, 🍔 내일은개발천재

#318 [Fix] 단축어 다운로드 숫자 업데이트
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: bug, 🐡 엘리

#319 [Feat] 큐레이션 편집에서 단축어 제거 시 단축어의 큐레이션 아이디 제거하는 함수 추가
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement, 🐡 엘리

#326 [Fix] 유저 정보가 없을 경우 처리
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
Labels: enhancement, 🐡 엘리

#324 [Feat] 서브타이틀 줄임표 없애기, 자동완성 막기
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
Labels: enhancement, 🍔 내일은개발천재

#321 [Fix] 큐레이션 모아보기 에러 수정 및 네비게이션 스택 리팩토링
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: enhancement, 🍔 내일은개발천재

#335 [Fix] 영어 검색 안되는 이슈 해결
  HappyAnding/HappyAnding/Views/SearchView.swift
Labels: enhancement, 🍔 내일은개발천재

#332 [Feat] 큐레이션 UI 업데이트 및 텍스트필드 업데이트
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Font+Extension.swift
  HappyAnding/HappyAnding/Views/Components/CustomTextEditor.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
Labels: enhancement

#331 [Fix] 큐레이션 단축어 셀 리스트 업데이트 에러
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
Labels: bug, 🐡 엘리

#329 [Feat] 다운로드한 단축어 셀 업데이트 아이콘 표시
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Image+Extension.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
Labels: enhancement, 🐡 엘리

#336 [Fix] 단축어 read view 뷰 밀리는 문제 해결
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement, 🍔 내일은개발천재
