Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2023-02, with the labels that each got.

#379 [Fix] 앱이 백그라운드에 없을 때, 비어있는 모달이 출력되는 문제
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: bug

#385 [Feat] TextLiteral 작업
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/RecentRegisteredView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MailView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
Labels: enhancement

#391 [Fix] 앱 삭제 후 재설치 시 유저정보가 남아있는 이슈 해결
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/ShareExtension/CustomShareViewController.swift
Labels: bug, 🐈 로겐시

#394 [Feat] Share Extension에 TextLiteral 적용 등의 리팩토링 및 수정
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Model/Category.swift
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/CustomShareViewController.swift
  HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift
  HappyAnding/ShareExtension/ShareExtensionViewModel.swift
  HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
Labels: enhancement, 🐈 로겐시

#400 [Fix] 좋아요 숫자 오류 해결
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
Labels: bug

#397 [Fix] #380 - swipe back 이슈 해결
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/View+Navigation.swift
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/Views/Components/CurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/RecentRegisteredView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
  HappyAnding/HappyAnding/Views/TabView/NavigationRouter.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
Labels: bug, 🍔 내일은개발천재

#395 [Fix] 댓글입력 창 레이아웃 오류 해결
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: bug, 🐈 로겐시

#402 [Feat] 카테고리를 표현하는 레이아웃 변경
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/wrappinghstack+license.txt
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
Labels: enhancement

#404 [Feat] 버전정보 처리방법 변경
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
Labels: enhancement
