Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2023-03, with the labels that each got.

#406 [Style] #401 - extension 컨벤션 적용
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Binding+Extension.swift
  HappyAnding/HappyAnding/Extensions/Color+Extension.swift
  HappyAnding/HappyAnding/Extensions/Date+String.swift
  HappyAnding/HappyAnding/Extensions/EnvironmentValues+Alerter.swift
  HappyAnding/HappyAnding/Extensions/Image+View.swift
  HappyAnding/HappyAnding/Extensions/LineBreaking+Extension.swift
  HappyAnding/HappyAnding/Extensions/String/String+Date.swift
  HappyAnding/HappyAnding/Extensions/String/String+Formatter.swift
  HappyAnding/HappyAnding/Extensions/UIApplication+Keyboard.swift
  HappyAnding/HappyAnding/Extensions/UIColor+Extension.swift
  HappyAnding/HappyAnding/Extensions/UIFont+Extension.swift
  HappyAnding/HappyAnding/Extensions/UINavigationContoller+Gesture.swift
  HappyAnding/HappyAnding/Extensions/UIScreen+Extension.swift
  HappyAnding/HappyAnding/Extensions/UIScreen+Size.swift
  HappyAnding/HappyAnding/Extensions/URL+DeepLink.swift
  HappyAnding/HappyAnding/Extensions/URL+Extension.swift
  HappyAnding/HappyAnding/Extensions/View+Navigation.swift
  HappyAnding/HappyAnding/Extensions/View/View+Gesture.swift
  HappyAnding/HappyAnding/Extensions/View/View+Navigation.swift
  HappyAnding/HappyAnding/Extensions/View/View+NavigationBar.swift
  HappyAnding/HappyAnding/Extensions/View/View+Shape.swift
  HappyAnding/HappyAnding/Extensions/View/View+UIFont.swift
  HappyAnding/HappyAnding/Views/TabView/NavigationRouter.swift
Labels: 🍔 내일은개발천재

#407 [Feat] SF Symbols 크기 및 weight 조정
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Image+View.swift
  HappyAnding/HappyAnding/Extensions/UIFont+Extension.swift
  HappyAnding/HappyAnding/Extensions/View/View+UIFont.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardView.swift
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift
  HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
Labels: enhancement, 🐈 로겐시

#416 [Feat] 단축어 작성 등급 안내 페이지 제작
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Assets.xcassets/Image/ShortcutGradeAnnouncement.imageset/Contents.json
  HappyAnding/HappyAnding/Assets.xcassets/Image/ShortcutGradeAnnouncement.imageset/ShortcutGradeAnnouncement 1.png
  HappyAnding/HappyAnding/Assets.xcassets/Image/ShortcutGradeAnnouncement.imageset/ShortcutGradeAnnouncement 2.png
  HappyAnding/HappyAnding/Assets.xcassets/Image/ShortcutGradeAnnouncement.imageset/ShortcutGradeAnnouncement.png
  HappyAnding/HappyAnding/Model/ShortcutGrade.swift
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
  HappyAnding/HappyAnding/Views/Components/AnnouncementCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/FeatureViews/AboutShortcutGradeView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
Labels: enhancement, 🐈 로겐시

#420 [fix] 폰트 변수명 변경
  HappyAnding/HappyAnding/Extensions/UIFont+Extension.swift
  HappyAnding/HappyAnding/Extensions/View/View+NavigationBar.swift
  HappyAnding/HappyAnding/Extensions/View/View+UIFont.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/AnnouncementCell.swift
  HappyAnding/HappyAnding/Views/Components/CustomTextEditor.swift
  HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
  HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/Components/MoreCaptionTextView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardView.swift
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/SubtitleTextView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
  HappyAnding/HappyAnding/Views/FeatureViews/AboutShortcutGradeView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/AboutTeamView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/CustomShareViewController.swift
  HappyAnding/ShareExtension/ShareExtensionCustomTextEditor.swift
  HappyAnding/ShareExtension/ShareExtensionTagTextField.swift
  HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift
  HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
Labels: enhancement, 🐈 로겐시

#418 [Fix] 단축어 버전 정보 화면의 레이아웃 오류 해결
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
Labels: bug, 🐈 로겐시
