Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2023-05, with the labels that each got.

#430 [Feat] 닉네임 수정 버튼 위치 변경 등의 UI 변경사항 (Apple Feedback)
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
Labels: enhancement, 🐈 로겐시

#440 [Feat] #425 ShowProfileView에서의 badge 회전 추가 (Apple Feedback)
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
Labels: enhancement

#442 [bug] ShortcutTabView의 Red 배경색 제거
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: bug

#443 [Feat] 작성자 닉네임 셀 디자인 통일
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/Components/UserNameCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
Labels: enhancement

#433 [Feat] IconModalView 심볼 추가
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
Labels: enhancement

#452 [Fix] 탭바로 맨 위로 스크롤
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: bug

#454 [Feat] 버전 확인 네비게이션으로 수정
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Assets.xcassets/versionAppIcon.imageset/AppIcon.png
  HappyAnding/HappyAnding/Assets.xcassets/versionAppIcon.imageset/Contents.json
  HappyAnding/HappyAnding/Extensions/View/View+Navigation.swift
  HappyAnding/HappyAnding/Model/NavigationStackModel.swift
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/CheckVersionView.swift
Labels: enhancement

#453 [Feat] Swipe 제스처 삭제
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
Labels: enhancement

#456 [Feat] TextEditor Keyboard Avoidance
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
Labels: enhancement
