Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2023-01, with the labels that each got.

#369 [Fix] #360 - 좋아요 수 업데이트
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
Labels: bug, 🍔 내일은개발천재

#372 [Feat] #371 로그인 없이 둘러보기
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
  HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
Labels: enhancement, 🐈 로겐시

#377 [Fix] ShortcutCell, CurationCell의 줄바꿈 문제 해결
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/LineBreaking+Extension.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
Labels: bug
