Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2023-10, with the labels that each got.

#483 [Feat] 단축어 및 댓글에 날짜 표시
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
Labels: enhancement, 🐈 로겐시

#497 [Fix] ShortcutCardCell 두 줄 표시 안 되는 문제 해결
  HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
Labels: bug

#499 [Refactor] foregroundColor(_:) -> foregroundStyle(_:) 로 변경
  HappyAnding/HappyAnding/Extensions/Image+View.swift
  HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/AnnouncementCell.swift
  HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
  HappyAnding/HappyAnding/Views/Components/MoreCaptionTextView.swift
  HappyAnding/HappyAnding/Views/Components/MyShortcutCardView.swift
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/SubtitleTextView.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
  HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
  HappyAnding/HappyAnding/Views/Components/UserNameCell.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadCurationView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListShortcutView.swift
  HappyAnding/HappyAnding/Views/FeatureViews/AboutShortcutGradeView.swift
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
  HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/AboutTeamView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/CheckVersionView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
  HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ShowProfileView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
  HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
  HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
  HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift
  HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
Labels: enhancement

#498 [Fix] 단축어 탭 ShortcutCell의 rankNumber 표시 오류 해결
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListShortcutView.swift
Labels: bug

#482 [Feat] 단축어 글쓰기 시 자동 타이틀 채우기
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
Labels: enhancement, 🐈 로겐시

#493 [Feat] 햅틱 피드백 추가
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Support/HapticManager.swift
  HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
  HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
  HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
  HappyAnding/HappyAnding/Views/FeatureViews/AboutShortcutGradeView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ShowProfileView.swift
  HappyAnding/HappyAnding/Views/ReadShortcutViews/UpdateShortcutView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
  HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
  HappyAnding/ShareExtension/CustomShareViewController.swift
  HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift
Labels: enhancement

#503 [Feat] 댓글 Copy 및 hypertext 추가
  HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
Labels: enhancement

#488 [Feat] push notification 받기 위한 설정
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Info.plist
  HappyAnding/HappyAnding/Support/AppDelegate.swift
  HappyAnding/HappyAnding/Views/HappyAndingApp.swift
Labels: enhancement
