Repository Team-ShortcutsZip/MacC-Team-HappyAnding, pull requests merged in 2024-04, with the labels that each got.

#522 [Feat] 공통 Extension 제작 등
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Assets.xcassets/Colors/CharcoalGray.colorset/Contents.json
  HappyAnding/HappyAnding/Extensions/View/View+Shadow.swift
  HappyAnding/HappyAnding/Extensions/View/View+Shape.swift
Labels: Type-Feature, Status-DoNotMerge

#519 [Feat] ExploreShortcutView 관련 UI 구현
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Assets.xcassets/bannerBg.imageset/Contents.json
  HappyAnding/HappyAnding/Assets.xcassets/bannerBg.imageset/bannerBg.png
  HappyAnding/HappyAnding/Extensions/Color+Extension.swift
  HappyAnding/HappyAnding/Extensions/SCZ+Color.swift
  HappyAnding/HappyAnding/Model/ExploreShortcutSectionType.swift
  HappyAnding/HappyAnding/Model/SectionType.swift
  HappyAnding/HappyAnding/TextLiteral.swift
  HappyAnding/HappyAnding/ViewModel/ExploreShortcutViewModels/ExploreShortcutViewModel.swift
  HappyAnding/HappyAnding/Views/Components/CardSection.swift
  HappyAnding/HappyAnding/Views/Components/ExploreCell.swift
  HappyAnding/HappyAnding/Views/Components/PromotionSection.swift
  HappyAnding/HappyAnding/Views/Components/Seal.swift
  HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExpandedRankingView.swift
  HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
  HappyAnding/HappyAnding/Views/SearchView.swift
  HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
Labels: Type-Feature, Status-Modify

#529 [Feat] Font / SFSymbol용 Extension 제작
  HappyAnding/HappyAnding.xcodeproj/project.pbxproj
  HappyAnding/HappyAnding/Extensions/Image+View.swift
  HappyAnding/HappyAnding/Extensions/View/View+Font.swift
  HappyAnding/HappyAnding/Info.plist
  HappyAnding/HappyAnding/Resources/Pretendard/Pretendard-Bold.otf
  HappyAnding/HappyAnding/Resources/Pretendard/Pretendard-Medium.otf
  HappyAnding/HappyAnding/Resources/Pretendard/Pretendard-Regular.otf
  HappyAnding/HappyAnding/Resources/Pretendard/Pretendard-SemiBold.otf
  HappyAnding/ShareExtension/Info.plist
Labels: Type-Feature
